version: "3.8"

services:
  db:
    image: mongo:6.0.5
    container_name: vidtube-mongodb
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./env/db.env
    networks:
      - vidtube-network

  backend:
    image: shyam2056/vidtube-backend
    container_name: vidtube-backend
    restart: always
    build:
      args:
        - NODE_ENV=development
      context: ./server
      target: development
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./env/server.env
    networks:
      - vidtube-network

  frontend:
    image: shyam2056/vidtube-frontend
    container_name: vidtube-frontend
    restart: always
    stdin_open: true
    tty: true
    build:
      args:
        - NODE_ENV=development
      context: ./client
      target: development
    volumes:
      - ./client/src:/client/src
      - /client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - ./env/client.env
    networks:
      - vidtube-network

volumes:
  db-data:

networks:
  vidtube-network:
