name: Docker Compose Build and Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_ENV: ${{ secrets.SERVER_ENV }}
      CLIENT_ENV: ${{ secrets.CLIENT_ENV }}
      DB_ENV: ${{ secrets.DB_ENV }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create env files
      run: |
        mkdir -p env
        echo $SERVER_ENV > env/server.env
        echo $CLIENT_ENV > env/client.env
        echo $DB_ENV > env/db.env
        cat env/server.env
        cat env/client.env
        cat  env/db.env
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker builder prune --all --force
        docker-compose build
        docker images
        docker-compose push
